/// \file Login.h
/*
*
* Login.h header template automatically generated by a class generator
* Creation date : ven. d�c. 16 2016
*
* This file is part of procctrl libraries.
*
* procctrl is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* based upon these libraries are permitted. Any copy of these libraries
* must include this copyright notice.
*
* procctrl is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with procctrl.  If not, see <http://www.gnu.org/licenses/>.
*
* @author Remi Ete
* @copyright CNRS , IPNL
*/


#ifndef LOGIN_H
#define LOGIN_H


namespace procctrl {

  namespace ui {

    /**
     *  @brief  Login class
     */
    class Login
    {
    public:
      /**
       *  @brief  Destructor
       */
      virtual ~Login() {}

      /**
       *
       */
      virtual bool login(const std::string &group, const std::string &password) = 0;

      /**
       *  @brief
       */
      virtual bool logout() = 0;

      /**
       *  @brief
       */
      virtual bool loggedIn() const = 0;
    };

  }

}

#endif  //  LOGIN_H
