/// \file Process.h
/*
*
* Process.h header template automatically generated by a class generator
* Creation date : ven. d�c. 16 2016
*
* This file is part of procctrl libraries.
*
* procctrl is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* based upon these libraries are permitted. Any copy of these libraries
* must include this copyright notice.
*
* procctrl is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with procctrl.  If not, see <http://www.gnu.org/licenses/>.
*
* @author Remi Ete
* @copyright CNRS , IPNL
*/


#ifndef PROCESS_H
#define PROCESS_H

// -- procctrl headers
#include "ProcCtrlInternal.h"

// -- json headers
#include "json/json.h"

namespace procctrl {

  /**
  * @brief Process class
  */
  class Process
  {
  public:
    std::string        m_name;           ///< The process name
    std::string        m_group;          ///< The process group
    std::string        m_program;        ///< The process program full name
    pid_t              m_pid;            ///< The process pid when running
    ProcessStatus      m_status;         ///< The process status
    Environnement      m_environement;   ///< The process environment variables
    ArgumentList       m_arguments;      ///< The process program arguments

  public:
    /**
     * @brief Constructor
     */
    Process();

    /**
     *  @brief
     */
    void fromJson(const Json::Value &value);

    /**
     *  @brief
     */
    void toJson(Json::Value &value) const;
  };

}

#endif  //  PROCESS_H
