/*
 *
 * ProcessManager.h header template automatically generated by a class generator
 * Creation date : lun. sept. 26 2016
 *
 * This file is part of procctrl libraries.
 * 
 * procctrl is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * procctrl is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with procctrl.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright Remi Ete
 */


#ifndef PROCCTRL_PROCESS_MANAGER_H
#define PROCCTRL_PROCESS_MANAGER_H 1

#include "ProcCtrlInternal.h"

namespace procctrl {

  namespace server {

    /**
     *  @brief  Process struct
     */
    struct Process
    {
      std::string        m_name;
      std::string        m_group;
      std::string        m_program;
      pid_t              m_pid;
      ProcessStatus      m_status;
      Environnement      m_environement;
      ArgumentList       m_arguments;
    };

    typedef std::map<std::string, Process> ProcessMap;

    /**
     * @brief ProcessManager class
     */
    class ProcessManager
    {
    public:
      /**
       *  @brief  Constructor
       */
      ProcessManager();

      /**
       *  @brief  Destructor
       */
      ~ProcessManager();

      /**
       *  @brief  Add a process
       */
      Status addProcess(
          const std::string &name,
          const std::string &group,
          const std::string &program,
          const ArgumentList &args,
          const Environnement &env
      );

      /**
       *  @brief  Start a registered process
       */
      Status startProcess(
          const std::string &name
      );

      /**
       *  @brief Restart a registered process
       */
      Status restartProcess(
          const std::string &name,
          KillSignal sig = SIGKILL
      );

      /**
       *  @brief  Remove a registered process. Kill the process if running
       */
      Status removeProcess(
          const std::string &name,
          KillSignal sig = SIGKILL
      );

      /**
       *  @brief  Kill a runnign process
       */
      Status killProcess(
          const std::string &name,
          KillSignal sig = SIGKILL
      );

      /**
       *  @brief  Kill all runing processes
       */
      Status killAllProcesses(
          KillSignal sig = SIGKILL
      );

      /**
       *  @brief  Get the process status
       */
      ProcessStatus getProcessStatus(
          const std::string &name
      ) const;

      /**
       *  @brief  Whether the process is registered
       */
      bool isProcessRegistered(
          const std::string &name
      ) const;

      /**
       *  @brief  Get the process group
       */
      Status getProcessGroup(
          const std::string &name,
          std::string &group
      ) const;

      /**
       *  @brief  Get the list of process name
       */
      std::vector<std::string> getProcessNames() const;

      /**
       *  @brief  Get the list of process name belonging to a particular group
       */
      std::vector<std::string> getProcessNames(
          const std::string &group
      ) const;

      /**
       *  @brief  Get the process log file content as a string
       */
      std::string getProcessLogFile(
          const std::string &name
      ) const;

      /**
       *  @brief  Modify the process environment. Valid only if the process is not running
       */
      Status modifyEnvironement(
          const std::string &name,
          const Environnement &env
      );

      /**
       *  @brief  Modify the process program. Valid only if the process is not running
       */
      Status modifyProgram(
          const std::string &name,
          const std::string &program
      );

      /**
       *  @brief  Modify the process arguments. Valid only if the process is not running
       */
      Status modifyArguments(
          const std::string &name,
          const ArgumentList &args
      );

    private:
      /**
       *  @brief  Start a registered process.
       *          Fork and calls execve()
       */
      Status startProcess(
          Process &process
      );

      /**
       *  @brief  Get the process status from the file system
       */
      ProcessStatus getProcessStatus(
          pid_t pid
      ) const;

    private:
      ProcessMap       m_processes;        ///< The process map
    };

  }

}

#endif  //  PROCCTRL_PROCESS_MANAGER_H
