language: cpp

sudo: not required

compilers:
  - gcc
  - clang

os:
  - linux
  - osx

script:
  - ./.travis.d/install_dependencies.sh
  - mkdir build
  - cd build
  - cmake ..
  - make install

matrix:
  include:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang
