language: cpp

sudo: not required

script:
  - ./.travis.d/install_dependencies.sh ${DIM_OS}
  - export DIMDIR=$PWD/dim
  - mkdir build
  - cd build
  - cmake -DDIMDIR=${DIMDIR} ..
  - make install

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

matrix:
  include:
    - os: osx
      compiler: gcc
      env:
        - DIM_OS=Darwin
    - os: linux
      compiler: clang
      env:
        - DIM_OS=Linux
    - os: osx
      compiler: clang
      env:
        - DIM_OS=Darwin
    - os: linux
      compiler: gcc
      env:
        - DIM_OS=Linux

notifications:
  email: false
