/// \file proctrl-generate-pwd.cc
/*
 *
 * proctrl-generate-pwd.cc source template automatically generated by a class generator
 * Creation date : jeu. sept. 29 2016
 *
 * This file is part of procctrl libraries.
 * 
 * procctrl is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * procctrl is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with procctrl.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright Remi Ete
 */

// -- procctrl headers
#include "ProcCtrlInternal.h"
#include "DbInterface.h"

// -- tclap headers
#include "tclap/CmdLine.h"
#include "tclap/Arg.h"

// -- openssl headers
#include <openssl/sha.h>

int main(int argc, char **argv)
{
  if(argc != 2)
  {
    std::cout << "Usage: procctrl-generate-pwd password" << std::endl;
    return 1;
  }

  const std::string password(argv[1]);
  procctrl::DbInterface db;
  unsigned char sha256[SHA256_DIGEST_LENGTH];

  db.passwordToSha256(password, sha256);

  for(int i=0 ; i<SHA256_DIGEST_LENGTH ; i++)
    printf("%x", sha256[i]);

  std::cout << std::endl;

  return 0;
}


